services:
  store_manager:
    profiles: ["app", "all"]
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - labo03-network
    depends_on:
      - mysql
      - redis

  mysql:
    profiles: ["db", "all"]
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    networks:
      - labo03-network
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 3s
      retries: 10

  redis:
    profiles: ["db", "all"]
    image: redis:7
    restart: unless-stopped
    networks:
      - labo03-network
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 2s
        timeout: 3s
        retries: 10

networks:
  labo03-network:
    driver: bridge
    external: true

volumes:
  mysql_data:
