name: CI
env:
  PYTHONPATH: src
  DB_HOST: localhost
  DB_PORT: 3306
  DB_NAME: labo03_db
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  REDIS_DB: 0

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Nettoyer le workspace
        run: |
          sudo rm -rf ${{ github.workspace }}/* || true
          sudo rm -rf ${{ github.workspace }}/.* || true
        continue-on-error: true

      - name: Checkout dépot
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Démarrer les services de base de données
        run: |
          docker compose --profile db up -d --wait

      - name: Exécuter les tests
        working-directory: src
        run: |
          python -m pytest
